From centos:7
LABEL creator = "tejal"
RUN yum install httpd -y
ADD https://www.free-css.com/assets/files/free-css-templates/download/page296/finexo.zip /var/www/html/
RUN rm -rf /var/www/html/index.html
Run yum install unzip -y
WORKDIR /var/www/html/
RUN unzip /var/www/html/finexo.zip
RUN mv finexo-html/*  .

EXPOSE 80
CMD httpd -DFOREGROUND